INSERT INTO D02.D02TB206_TIPO_CONTEUDO (NU_TIPO_CONTEUDO,CO_CONTEUDO,NO_TIPO_CONTEUDO) VALUES (1,'N','Nao Se Aplica (vazio)');
INSERT INTO D02.D02TB206_TIPO_CONTEUDO (NU_TIPO_CONTEUDO,CO_CONTEUDO,NO_TIPO_CONTEUDO) VALUES (2,'P','Copia CIF Principal');
INSERT INTO D02.D02TB206_TIPO_CONTEUDO (NU_TIPO_CONTEUDO,CO_CONTEUDO,NO_TIPO_CONTEUDO) VALUES (3,'I','Copia CIF Princ. Inverte Sinal');
INSERT INTO D02.D02TB206_TIPO_CONTEUDO (NU_TIPO_CONTEUDO,CO_CONTEUDO,NO_TIPO_CONTEUDO) VALUES (4,'E','Conteudo especifico');